sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - DRIVER_VERSION=1.1.1 LEGACY_DRIVER_VERSION=""
    - DRIVER_VERSION=1.1.1 LEGACY_DRIVER_VERSION=1.6.12

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

before_script:
  - pecl install -f mongodb-${DRIVER_VERSION}
  - if [ "x$LEGACY_DRIVER_VERSION" != "x" ]; then yes '' | pecl -q install -f mongo-${LEGACY_DRIVER_VERSION}; fi
  - composer install

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
